bump in contrib aws libs version
```
ya tool yo get github.com/aws/aws-sdk-go@v1.55.7
ya tool yo get github.com/aws/aws-sdk-go-v2@v1.39.2
ya tool yo get github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream@v1.7.1
ya tool yo get github.com/aws/aws-sdk-go-v2/config@v1.31.12
ya tool yo get github.com/aws/aws-sdk-go-v2/credentials@v1.18.16
ya tool yo get github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.18.9
ya tool yo get github.com/aws/aws-sdk-go-v2/feature/s3/manager@v1.17.84
ya tool yo get github.com/aws/aws-sdk-go-v2/service/kms@v1.41.2
ya tool yo get github.com/aws/aws-sdk-go-v2/service/s3@v1.88.3
ya tool yo get github.com/aws/aws-sdk-go-v2/service/secretsmanager@v1.35.7
ya tool yo get github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue@v1.19.5
ya tool yo get github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression@v1.7.87
ya tool yo get github.com/aws/aws-sdk-go-v2/internal/configsources@v1.4.9
ya tool yo get github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.7.9
ya tool yo get github.com/aws/aws-sdk-go-v2/internal/ini@v1.8.3
ya tool yo get github.com/aws/aws-sdk-go-v2/internal/v4a@v1.4.9
ya tool yo get github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.44.0
ya tool yo get github.com/aws/aws-sdk-go-v2/service/dynamodbstreams@v1.26.0
ya tool yo get github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding@v1.13.1
ya tool yo get github.com/aws/aws-sdk-go-v2/service/internal/checksum@v1.8.9
ya tool yo get github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery@v1.10.17
ya tool yo get github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.13.9
ya tool yo get github.com/aws/aws-sdk-go-v2/service/internal/s3shared@v1.19.9
ya tool yo get github.com/aws/aws-sdk-go-v2/service/sqs@v1.38.8
ya tool yo get github.com/aws/aws-sdk-go-v2/service/sso@v1.29.6
ya tool yo get github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.35.1
ya tool yo get github.com/aws/aws-sdk-go-v2/service/sts@v1.38.6

ya tool yo vendor
```

падают:

```
vendor/github.com/aws/aws-sdk-go-v2/service/kms/gotest
    TestEndpointCase61
        endpoints_test.go:2287: expect error, got none
    TestEndpointCase62
        endpoints_test.go:2307: expect error, got none
    TestEndpointCase65
        endpoints_test.go:2401: expect error, got none
    TestEndpointCase66
        endpoints_test.go:2421: expect error, got none

vendor/github.com/aws/aws-sdk-go-v2/service/secretsmanager/gotest
    TestEndpointCase41
        endpoints_test.go:1547: expect error, got none
    TestEndpointCase43
        endpoints_test.go:1604: expect error, got none
    TestEndpointCase44
        endpoints_test.go:1624: expect error, got none
    TestEndpointCase46
        endpoints_test.go:1681: expect error, got none

vendor/github.com/aws/aws-sdk-go-v2/service/sqs/gotest
    TestEndpointCase40
        endpoints_test.go:1510: expect error, got none
    TestEndpointCase42
        endpoints_test.go:1567: expect error, got none
    TestEndpointCase44
        endpoints_test.go:1624: expect error, got none
    TestEndpointCase46
        endpoints_test.go:1681: expect error, got none
```

Роботы ищут проблему в согласованности версий:

> Уже видно закономерность: ваши kms/secretsmanager/sqs реально сидят на более старой генерации endpoint-резолвера, поэтому при поднятых internal/\* тесты меняют поведение.

```
ya tool yo get github.com/aws/aws-sdk-go-v2/service/kms@v1.50.0
ya tool yo get github.com/aws/aws-sdk-go-v2/service/secretsmanager@v1.41.1
ya tool yo get github.com/aws/aws-sdk-go-v2/service/sqs@v1.42.21
ya tool yo get github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.55.0
ya tool yo get github.com/aws/aws-sdk-go-v2/service/dynamodbstreams@v1.32.10
ya tool yo get github.com/aws/aws-sdk-go-v2/feature/s3/manager@v1.22.1
ya tool yo get github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue@v1.20.32
ya tool yo get github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression@v1.8.32
ya tool yo get github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery@v1.11.17
```

также пофиксил завязки на недокументированные вещи которые оказались выкинуты:

```
$(SOURCE_ROOT)/saas/infractl/internal/ycsync/yc.go:145:21: undefined: types.LifecycleRuleFilterMemberPrefix
$(SOURCE_ROOT)/mlplatform/underdeep/library/go/s3/snapshots.go:281:18: undefined: types.LifecycleRuleFilterMemberPrefix
$(SOURCE_ROOT)/infra/dist_2/pkg/clients/s3/client.go:886:21: undefined: types.LifecycleRuleFilterMemberPrefix
```

\-\>

```
github.com/aws/aws-sdk-go-v2/config (Go) vendor/github.com/aws/aws-sdk-go-v2/config version 1.32.8 still under quarantine (until 2026-03-03 19:51:34)
github.com/aws/aws-sdk-go-v2/credentials (Go) vendor/github.com/aws/aws-sdk-go-v2/credentials version 1.19.8 still under quarantine (until 2026-03-03 19:51:34)
github.com/aws/aws-sdk-go-v2/feature/s3/manager (Go) vendor/github.com/aws/aws-sdk-go-v2/feature/s3/manager version 1.22.1 still under quarantine (until 2026-03-03 19:51:34)
github.com/aws/aws-sdk-go-v2/service/kms (Go) vendor/github.com/aws/aws-sdk-go-v2/service/kms version 1.50.0 still under quarantine (until 2026-03-02 19:22:12)
github.com/aws/aws-sdk-go-v2/service/ssooidc (Go) vendor/github.com/aws/aws-sdk-go-v2/service/ssooidc version 1.35.14 still under quarantine (until 2026-03-03 19:51:34)
```

чутка даунгрейжусь, с 3го коммита применю такие bump'ы:

```
ya tool yo get github.com/aws/aws-sdk-go-v2/config@v1.32.7
ya tool yo get github.com/aws/aws-sdk-go-v2/credentials@v1.19.7
ya tool yo get github.com/aws/aws-sdk-go-v2/feature/s3/manager@v1.21.1
ya tool yo get github.com/aws/aws-sdk-go-v2/service/kms@v1.49.5
ya tool yo get github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.35.13
ya tool yo get github.com/aws/aws-sdk-go-v2/service/secretsmanager@v1.41.1
ya tool yo get github.com/aws/aws-sdk-go-v2/service/sqs@v1.42.21
ya tool yo get github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.55.0
ya tool yo get github.com/aws/aws-sdk-go-v2/service/dynamodbstreams@v1.32.10
ya tool yo get github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue@v1.20.32
ya tool yo get github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression@v1.8.32
ya tool yo get github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery@v1.11.17
```
commit_hash:46002861da9a18bc43201c61e870928f0e33e383